name: Ninchat SwiftSDK

on:
  push:
    branches:
      - '*'
      - '*/*'

jobs:
  build_test_SDK:
    runs-on: macos-13

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Select Xcode 14.2
        run: sudo xcode-select -s "/Applications/Xcode_14.2.app/Contents/Developer"

      - name: Verify Xcode
        run: |
          xcode-select -p
          xcodebuild -version

      - name: Install CocoaPods
        run: pod update

      - name: Build & Test (Unit Tests Only)
        run: |
          xcodebuild test \
            -workspace NinchatSDKSwift.xcworkspace \
            -scheme NinchatSDKSwiftTests \
            -destination "platform=iOS Simulator,name=iPhone 14" \
            "OTHER_LDFLAGS=$(OTHER_LDFLAGS) -read_only_relocs suppress" \
            ONLY_ACTIVE_ARCH=YES
