on:
  push:
    branches:
      - '*'
      - '*/*'
      
jobs:
  build_test_SDK:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Select Xcode 14.2
        uses: actions/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Verify Xcode
        run: |
          xcode-select -p
          xcodebuild -version

      - name: Install CocoaPods
        run: pod update

      - name: Build & Test
        run: |
          xcodebuild test \
            -workspace NinchatSDKSwift.xcworkspace \
            -scheme NinchatSDKSwift \
            -destination "platform=iOS Simulator,name=iPhone 14" \
            "OTHER_LDFLAGS=$(OTHER_LDFLAGS) -read_only_relocs suppress" \
            ONLY_ACTIVE_ARCH=YES
